### ISSUE TITLE
/bin/sh a source

### ISSUE THREAD

**Issue by ElectricPulse** [JozefGalbicka/websupportsk-ddns#2]
Bourne shell neposkytuje source prikaz  v run-sync

**Comment by JozefGalbicka** [comment]
Fixed v 028983b, skript bol ale nahradeny za Makefile target, pretoze som redukoval ten zbytocny balast vratane venv-u v docker image.. takze po novom `make -C /path/to/project/websupportsk-ddns run-dockerless`. Popripade si vytiahnut ten command do shell skriptu.
